version: "3"

services:
  nginx: 
    ports:
      - 3000:80
  node_app:
    build:
      args: 
        - NODE_ENV:dev
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=dev
    command: npm run dev